if(FALSE){
    library(funcTools)
    rQsub2("./", "10_evaluateOnInterferon_GSE31019_v0.99.14.R", 
           jobName = "Job_10", threaded = 2, memoryG = "50", 
           rTimeHour = 20, logFile = "logFile_10.log", 
           email = "w.tao-2@umcutrecht.nl", 
           preCMD = "Rscript ", param1 = 1)
    qstat2()
}
# setwd("/hpc/dla_lti/wtao/")
rm(list = ls())
gc(reset = TRUE)
options(max.print = 100)
commandArgs()

source("0_functionsInThePaper.R")
# GPL6244 platform, [HuGene-1_0-st] Affymetrix Human Gene 1.0 ST Array [transcript (gene) version]
# Total number of rows: 33297


############ Suppression of IFN-Induced Transcription Underlies IFN Defects Generated by Activated Ras/MEK in Human Cancer Cells (IFNa)
geoAcession = "GSE31019"
if(file.exists("../rData/10_gds.Rdata")){
    cat("load ", "../rData/10_gds.Rdata", "\n")
    load("../rData/10_gds.Rdata")
} else {
    folder = paste0("../rawData/Interferon/", geoAcession, "/")
    library(GEOquery)
    exprFile = normalizePath(dir(folder, pattern = "*.txt", full.names = T))
    print(exprFile)
    gds <- getGEO(filename=exprFile)
    save(gds, file = "../rData/10_gds.Rdata")
}

{
    expr = exprs(gds)
    pd0 = pData(gds)
    pd = pd0[, c("title", "geo_accession", "cell line:ch1", "time:ch1", "treatment:ch1")]
    colnames(pd) = c("title", "geo_accession", "cell", "time", "group")
    pd$cell = c(`HT1080 human fibrosarcoma cell line` = "HT1080", 
                `SKOV3 human ovarian adenocarcinoma cell line` = "SKOV3")[pd$cell]
    pd$time = as.numeric(strSplit(pd$time, "h")[,1])
    pd$group = as.factor(pd$group)
    pData(gds) = pd
    
    edata = gds[, pd$group %in% c("control", "IFN")]
}


# eSet
library(RegEnrich)
data(TFs)
regulators = c(unique(TFs$TF_name))
# Healthy donor

######## cells
cells = c("HT1080", "SKOV3")
np = c("1p", "5p", "3p")[2]
for (cell in cells){
    file = paste0("../rData/object_10_", geoAcession, "_", 
                  cell, ".Rdata")
    if (file.exists(file)){
        cat("load ", file, "\n")
        load(file)
    } else {
        # IFNa2
        edata_2 = edata[, pData(edata)$cell == cell]
        pData(edata_2)$group = droplevels(pData(edata_2)$group)
        
        # 
        fdata = fData(edata_2)
        gene0 = strSplit(fdata$gene_assignment, " // ")[,2]
        expr = exprs(edata_2)[!duplicated(gene0),]
        fdata = fdata[!duplicated(gene0), ]
        # expr = preprocessCore::normalize.quantiles(expr)
        rownames(expr) = gene0[!duplicated(gene0)]
        pdata = pData(edata_2)
        
        
        softPower = ifelse(cell == "SKOV3", 20, 12)
        
        if(cell == "HT1080"){
            design = ~ time + group
            reduced = ~ time
        } else {
            design = ~ group
            reduce = ~ 1
        }
        
        ### RegEnrich
        library(BiocParallel)
        bpparam = register(MulticoreParam(2))
        object = RegenrichSet(expr, colData = pdata, method = "LRT_LM", 
                              minMeanExpr = 4, 
                              design = design, reduced = reduced, 
                              reg = regulators, 
                              BPPARAM = bpparam,
                              networkConstruction = 'COEN',
                              softPower = softPower,
                              enrichTest = 'FET')
        print(dim(object))
        object = object %>% regenrich_diffExpr() %>% 
            regenrich_network() %>% 
            regenrich_enrich() %>% 
            regenrich_rankScore()
        save(object, file = file)
    }
    
    score = results_score(object)
    write.table(score, paste0("../rData/score_10_", geoAcession, "_", 
                              cell, "_FET.tsv"), sep = "\t")
    
    ## COEN + GSEA
    file2 = paste0("../rData/object_10_", geoAcession, "_", 
                   cell, "_GSEA.Rdata")
    if (file.exists(file2)){
        cat("load ", file2, "\n")
        load(file2)
    } else {
        object = object %>% 
            regenrich_enrich(enrichTest = "GSEA") %>% 
            regenrich_rankScore()
        save(object, file = file2)
    }
    score = results_score(object)
    write.table(score, paste0("../rData/score_10_", geoAcession, "_", 
                              cell, "_GSEA.tsv"), sep = "\t")
    
}